replicaCount: 1
image:
  repository: ipaasvertigo/devportal
  tag: 0.1.0
  pullPolicy: IfNotPresent
#imagePullSecrets:
nodeEnv: development
service:
  name: devportal
  type: ClusterIP
  containerPort: 7007
ingress:
  enabled: false
  #ingressClassName: "nginx"
  #annotations: {}
  #hosts:
    #- host: 
      #paths:
        #- path: /
          #pathType: 
#resources:
  #requests:
    #memory: 512Mi
  #limits:
    #memory: 1024Mi
appConfig:
  app:
    baseUrl: 
  backend:
    baseUrl: 
auth:
  okta:
    clientId: lore
    clientSecret: lore
    audience: lore
githubToken: lore
githubSpecHouseURL: lore
