apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: youroktetonamespace
type: Opaque
# Uncomment thoose lines below and fill with your okta credentials
# data:
#   OKTA_CLIENT_ID: 
#   OKTA_CLIENT_SECRET: 
#   OKTA_CLIENT_DOMAIN: 
#   GITHUB_SPECHOUSE_URL: 
#   GITHUB_TOKEN: